name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v5
      - name: Set-up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.1'
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4
      - run: opam install . --deps-only --with-test --with-dev-setup
      - run: opam exec -- dune build @check
      - run: opam exec -- dune runtest
      - run: opam exec -- zanuda -dir .
      - run: go test -v
        working-directory: go
